options:
  administrator-password:
    type: string
    description: |
      The password for the default local administrator user.
      If set to an empty value, the default local administrator password will not be changed. This
        can be the case for various providers like AWS, where the default local
        administrator user password is already set. In the case that the provider
        does not set a strong password for the default local administrator,
        make sure to specify a strong password.
      A strong password for the default local administrator is a requirement for
      Active Directory Domain installation.
      To enable scaling, a strong password must be provided, as it is needed to
        promote an active directory node to an active directory controller.
      The value must conform to the password requirements
      described at: https://technet.microsoft.com/en-us/library/cc786468(v=ws.10).aspx
  safe-mode-password:
    type: string
    description: |
      The safe mode password for the Active Directory.
      A strong safe mode password is a requirement for
      Active Directory Domain installation.
      The value must conform to the password requirements
      described at: https://technet.microsoft.com/en-us/library/cc786468(v=ws.10).aspx
  domain-user:
    type: string
    default: 'jujuadmin'
    description: |
      The default domain user that will be exposed by the Active Directory charm relation.
      It can be used by the charms that are in relation to connect to the
      Active Directory domain, as only a Domain user has the rights to connect
      a machine to that domain.
      This value is required vor the Active Directory installation.
  domain-user-password:
    type: string
    description: |
      The password for the default domain user. This value is required.
      This value must conform to the password requirements
      described at: https://technet.microsoft.com/en-us/library/cc786468(v=ws.10).aspx
  domain-name:
    type: string
    default: 'cloudbase.local'
    description: |
      The Active Directory fully quallyfied domain name.
      This value is required vor the Active Directory installation.
      The format of the domain name must be <netbios domain name>.<domain-suffix>
      If this value is changed after the domain install, no changes will be performed.
  open-all-active-directory-ports:
    type: boolean
    default: False
    description: |
      The Active Directory Controllers have, by default, WinRM, RDP, LDAP(S),
      DNS and Kerberos ports opened. When set to True, the other Active
      Directory ports specified by Microsoft will be opened:
      https://technet.microsoft.com/en-us/library/dd772723(v=ws.10).aspx
  change-hostname:
    default: False
    type: boolean
    description: |
      The hostname set inside the newly spawned machine is usually the same as
      the name of the instance being spawned. In cases where the instance name
      is larger then 15 characters (maximum size for windows NetBios names), the
      instance name gets truncated to the first 15 characters. This creates a problem,
      as hostnames in active directory, for example, are very important. Having more
      then one machine with the same hostname try to join the same domain, will
      create trust issues.
      This option allows changing the hostname of the current running system to a
      combination of the first 14 (or less, depending on how many digits the unit number has)
      characters of the charm name and the unit number. While this is not infallible,
      It does have less of a chance of creating hostname conflicts.
  ca-common-name:
    default: cloudbase
    type: string
    description: |
      The common name used for the AD certificate authority set up by the charm.
  enable-san-certificates:
    default: False
    type: boolean
    description: |
      Boolean option to indicate whether SAN certificates are enabled or not
      for the AD certificate authority.